// Code generated by "stringer -type=BuildStatus"; DO NOT EDIT.

package types

import "strconv"

const _BuildStatus_name = "StuckRunningSuccessFailedCancelledWaiting"

var _BuildStatus_index = [...]uint8{0, 5, 12, 19, 25, 34, 41}

func (i BuildStatus) String() string {
	i -= 1
	if i < 0 || i >= BuildStatus(len(_BuildStatus_index)-1) {
		return "BuildStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BuildStatus_name[_BuildStatus_index[i]:_BuildStatus_index[i+1]]
}
