// Code generated by "stringer -type=BuildStatus"; DO NOT EDIT.

package types

import "strconv"

const _BuildStatus_name = "BS_STUCKBS_RUNNINGBS_SUCCESSBS_FAILEDBS_CANCELLEDBS_WAITING"

var _BuildStatus_index = [...]uint8{0, 8, 18, 28, 37, 49, 59}

func (i BuildStatus) String() string {
	i -= 1
	if i < 0 || i >= BuildStatus(len(_BuildStatus_index)-1) {
		return "BuildStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _BuildStatus_name[_BuildStatus_index[i]:_BuildStatus_index[i+1]]
}
