// Code generated by "stringer -type=ContainerStatus"; DO NOT EDIT.

package types

import "strconv"

const _ContainerStatus_name = "CS_RUNNINGCS_STARTEDCS_STOPPED"

var _ContainerStatus_index = [...]uint8{0, 10, 20, 30}

func (i ContainerStatus) String() string {
	i -= 1
	if i < 0 || i >= ContainerStatus(len(_ContainerStatus_index)-1) {
		return "ContainerStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ContainerStatus_name[_ContainerStatus_index[i]:_ContainerStatus_index[i+1]]
}
