FROM mongo:latest

MAINTAINER Ghazni Nattarshah <ghazni.nattarshah@conspico.com>

#COPY mongo.conf /usr/local/etc/mongo/mongo.conf

#VOLUME /data/db /data/configdb

# ADD init.js init.js

CMD ["mongod"]

EXPOSE 27017
