// Code generated by protoc-gen-go.
// source: pb/auth.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/auth.proto
	pb/client.proto
	pb/user.proto

It has these top-level messages:
	AuthorizeReq
	AuthorizeRes
	ClientMsg
	CreateReq
	CreateRes
	DeleteReq
	DeleteRes
	SignUpReq
	SignUpRes
	SignInReq
	SignInRes
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthorizeReq struct {
	Scope        []string `protobuf:"bytes,1,rep,name=scope" json:"scope,omitempty"`
	ResponseType string   `protobuf:"bytes,2,opt,name=response_type,json=responseType" json:"response_type,omitempty"`
	ClientId     string   `protobuf:"bytes,3,opt,name=client_id,json=clientId" json:"client_id,omitempty"`
	State        string   `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
	Nonce        string   `protobuf:"bytes,5,opt,name=nonce" json:"nonce,omitempty"`
	Prompt       string   `protobuf:"bytes,6,opt,name=prompt" json:"prompt,omitempty"`
	MaxAge       string   `protobuf:"bytes,7,opt,name=max_age,json=maxAge" json:"max_age,omitempty"`
	Display      string   `protobuf:"bytes,8,opt,name=display" json:"display,omitempty"`
}

func (m *AuthorizeReq) Reset()                    { *m = AuthorizeReq{} }
func (m *AuthorizeReq) String() string            { return proto.CompactTextString(m) }
func (*AuthorizeReq) ProtoMessage()               {}
func (*AuthorizeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthorizeReq) GetScope() []string {
	if m != nil {
		return m.Scope
	}
	return nil
}

func (m *AuthorizeReq) GetResponseType() string {
	if m != nil {
		return m.ResponseType
	}
	return ""
}

func (m *AuthorizeReq) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *AuthorizeReq) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AuthorizeReq) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *AuthorizeReq) GetPrompt() string {
	if m != nil {
		return m.Prompt
	}
	return ""
}

func (m *AuthorizeReq) GetMaxAge() string {
	if m != nil {
		return m.MaxAge
	}
	return ""
}

func (m *AuthorizeReq) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

type AuthorizeRes struct {
	Created bool `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
}

func (m *AuthorizeRes) Reset()                    { *m = AuthorizeRes{} }
func (m *AuthorizeRes) String() string            { return proto.CompactTextString(m) }
func (*AuthorizeRes) ProtoMessage()               {}
func (*AuthorizeRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthorizeRes) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func init() {
	proto.RegisterType((*AuthorizeReq)(nil), "pb.AuthorizeReq")
	proto.RegisterType((*AuthorizeRes)(nil), "pb.AuthorizeRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	Authorize(ctx context.Context, in *AuthorizeReq, opts ...grpc.CallOption) (*AuthorizeRes, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Authorize(ctx context.Context, in *AuthorizeReq, opts ...grpc.CallOption) (*AuthorizeRes, error) {
	out := new(AuthorizeRes)
	err := grpc.Invoke(ctx, "/pb.Auth/Authorize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	Authorize(context.Context, *AuthorizeReq) (*AuthorizeRes, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Auth/Authorize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Authorize(ctx, req.(*AuthorizeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authorize",
			Handler:    _Auth_Authorize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/auth.proto",
}

func init() { proto.RegisterFile("pb/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4e, 0x84, 0x30,
	0x14, 0x85, 0xc3, 0xfc, 0xd3, 0x0c, 0xd1, 0x34, 0xfe, 0x34, 0xa3, 0x0b, 0x82, 0x1b, 0x56, 0x10,
	0xf5, 0x09, 0x66, 0x63, 0xe2, 0xc6, 0x05, 0x71, 0x4f, 0x0a, 0xdc, 0x30, 0x4d, 0xa0, 0xbd, 0xd2,
	0x8e, 0x19, 0x5c, 0xfa, 0x0a, 0x3e, 0x9a, 0x6b, 0x77, 0x3e, 0x88, 0xa1, 0x15, 0xa3, 0x2e, 0xbf,
	0xef, 0x9c, 0x36, 0xb9, 0x87, 0x04, 0x58, 0xa4, 0x7c, 0x6f, 0x76, 0x09, 0x76, 0xca, 0x28, 0x3a,
	0xc1, 0x62, 0x73, 0x59, 0x2b, 0x55, 0x37, 0x90, 0x72, 0x14, 0x29, 0x97, 0x52, 0x19, 0x6e, 0x84,
	0x92, 0xda, 0x35, 0xa2, 0x0f, 0x8f, 0xac, 0xb7, 0x7b, 0xb3, 0x53, 0x9d, 0x78, 0x81, 0x0c, 0x9e,
	0xe8, 0x09, 0x99, 0xeb, 0x52, 0x21, 0x30, 0x2f, 0x9c, 0xc6, 0x7e, 0xe6, 0x80, 0x5e, 0x91, 0xa0,
	0x03, 0x8d, 0x4a, 0x6a, 0xc8, 0x4d, 0x8f, 0xc0, 0x26, 0xa1, 0x17, 0xfb, 0xd9, 0x7a, 0x94, 0x8f,
	0x3d, 0x02, 0xbd, 0x20, 0x7e, 0xd9, 0x08, 0x90, 0x26, 0x17, 0x15, 0x9b, 0xda, 0xc2, 0xca, 0x89,
	0xfb, 0xca, 0xfe, 0x6b, 0xb8, 0x01, 0x36, 0xb3, 0x81, 0x83, 0xc1, 0x4a, 0x25, 0x4b, 0x60, 0x73,
	0x67, 0x2d, 0xd0, 0x33, 0xb2, 0xc0, 0x4e, 0xb5, 0x68, 0xd8, 0xc2, 0xea, 0x6f, 0xa2, 0xe7, 0x64,
	0xd9, 0xf2, 0x43, 0xce, 0x6b, 0x60, 0x4b, 0x17, 0xb4, 0xfc, 0xb0, 0xad, 0x81, 0x32, 0xb2, 0xac,
	0x84, 0xc6, 0x86, 0xf7, 0x6c, 0x65, 0x83, 0x11, 0xa3, 0xf8, 0xcf, 0x79, 0x7a, 0x68, 0x96, 0x1d,
	0x70, 0x03, 0x15, 0xf3, 0x42, 0x2f, 0x5e, 0x65, 0x23, 0xde, 0x3c, 0x90, 0xd9, 0xd0, 0xa4, 0x77,
	0xc4, 0xff, 0x79, 0x41, 0x8f, 0x13, 0x2c, 0x92, 0xdf, 0xfb, 0x6c, 0xfe, 0x1b, 0x1d, 0x9d, 0xbe,
	0xbe, 0x7f, 0xbe, 0x4d, 0x8e, 0x68, 0x90, 0x3e, 0x5f, 0xdb, 0xf1, 0x6d, 0x52, 0x2c, 0xec, 0xc0,
	0xb7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xe3, 0xc8, 0x9c, 0x93, 0x01, 0x00, 0x00,
}
