// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/shift.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterReq struct {
	BuildId              string   `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Privatekey           string   `protobuf:"bytes,2,opt,name=privatekey,proto3" json:"privatekey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3bad42b4e7b5cf, []int{0}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetBuildId() string {
	if m != nil {
		return m.BuildId
	}
	return ""
}

func (m *RegisterReq) GetPrivatekey() string {
	if m != nil {
		return m.Privatekey
	}
	return ""
}

type RegisterRes struct {
	Registered           bool     `protobuf:"varint,1,opt,name=registered,proto3" json:"registered,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRes) Reset()         { *m = RegisterRes{} }
func (m *RegisterRes) String() string { return proto.CompactTextString(m) }
func (*RegisterRes) ProtoMessage()    {}
func (*RegisterRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3bad42b4e7b5cf, []int{1}
}

func (m *RegisterRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRes.Unmarshal(m, b)
}
func (m *RegisterRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRes.Marshal(b, m, deterministic)
}
func (m *RegisterRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRes.Merge(m, src)
}
func (m *RegisterRes) XXX_Size() int {
	return xxx_messageInfo_RegisterRes.Size(m)
}
func (m *RegisterRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRes.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRes proto.InternalMessageInfo

func (m *RegisterRes) GetRegistered() bool {
	if m != nil {
		return m.Registered
	}
	return false
}

type UpdateBuildStatusReq struct {
	BuildId              string   `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Graph                string   `protobuf:"bytes,2,opt,name=graph,proto3" json:"graph,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Checkpoint           string   `protobuf:"bytes,4,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	Reason               string   `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Duration             string   `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBuildStatusReq) Reset()         { *m = UpdateBuildStatusReq{} }
func (m *UpdateBuildStatusReq) String() string { return proto.CompactTextString(m) }
func (*UpdateBuildStatusReq) ProtoMessage()    {}
func (*UpdateBuildStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3bad42b4e7b5cf, []int{2}
}

func (m *UpdateBuildStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBuildStatusReq.Unmarshal(m, b)
}
func (m *UpdateBuildStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBuildStatusReq.Marshal(b, m, deterministic)
}
func (m *UpdateBuildStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBuildStatusReq.Merge(m, src)
}
func (m *UpdateBuildStatusReq) XXX_Size() int {
	return xxx_messageInfo_UpdateBuildStatusReq.Size(m)
}
func (m *UpdateBuildStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBuildStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBuildStatusReq proto.InternalMessageInfo

func (m *UpdateBuildStatusReq) GetBuildId() string {
	if m != nil {
		return m.BuildId
	}
	return ""
}

func (m *UpdateBuildStatusReq) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *UpdateBuildStatusReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateBuildStatusReq) GetCheckpoint() string {
	if m != nil {
		return m.Checkpoint
	}
	return ""
}

func (m *UpdateBuildStatusReq) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *UpdateBuildStatusReq) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

type UpdateBuildStatusRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBuildStatusRes) Reset()         { *m = UpdateBuildStatusRes{} }
func (m *UpdateBuildStatusRes) String() string { return proto.CompactTextString(m) }
func (*UpdateBuildStatusRes) ProtoMessage()    {}
func (*UpdateBuildStatusRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3bad42b4e7b5cf, []int{3}
}

func (m *UpdateBuildStatusRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBuildStatusRes.Unmarshal(m, b)
}
func (m *UpdateBuildStatusRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBuildStatusRes.Marshal(b, m, deterministic)
}
func (m *UpdateBuildStatusRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBuildStatusRes.Merge(m, src)
}
func (m *UpdateBuildStatusRes) XXX_Size() int {
	return xxx_messageInfo_UpdateBuildStatusRes.Size(m)
}
func (m *UpdateBuildStatusRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBuildStatusRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBuildStatusRes proto.InternalMessageInfo

type GetProjectReq struct {
	BuildId              string   `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	IncludeShiftfile     bool     `protobuf:"varint,2,opt,name=include_shiftfile,json=includeShiftfile,proto3" json:"include_shiftfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectReq) Reset()         { *m = GetProjectReq{} }
func (m *GetProjectReq) String() string { return proto.CompactTextString(m) }
func (*GetProjectReq) ProtoMessage()    {}
func (*GetProjectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3bad42b4e7b5cf, []int{4}
}

func (m *GetProjectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectReq.Unmarshal(m, b)
}
func (m *GetProjectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectReq.Marshal(b, m, deterministic)
}
func (m *GetProjectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectReq.Merge(m, src)
}
func (m *GetProjectReq) XXX_Size() int {
	return xxx_messageInfo_GetProjectReq.Size(m)
}
func (m *GetProjectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectReq proto.InternalMessageInfo

func (m *GetProjectReq) GetBuildId() string {
	if m != nil {
		return m.BuildId
	}
	return ""
}

func (m *GetProjectReq) GetIncludeShiftfile() bool {
	if m != nil {
		return m.IncludeShiftfile
	}
	return false
}

type GetProjectRes struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	RepositoryId         string   `protobuf:"bytes,2,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	VcsId                string   `protobuf:"bytes,3,opt,name=vcs_id,json=vcsId,proto3" json:"vcs_id,omitempty"`
	Branch               string   `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	CloneUrl             string   `protobuf:"bytes,6,opt,name=clone_url,json=cloneUrl,proto3" json:"clone_url,omitempty"`
	Language             string   `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	Accesstoken          string   `protobuf:"bytes,8,opt,name=accesstoken,proto3" json:"accesstoken,omitempty"`
	CommitId             string   `protobuf:"bytes,9,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	StoragePath          string   `protobuf:"bytes,10,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	Source               string   `protobuf:"bytes,11,opt,name=source,proto3" json:"source,omitempty"`
	Shiftfile            string   `protobuf:"bytes,12,opt,name=shiftfile,proto3" json:"shiftfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProjectRes) Reset()         { *m = GetProjectRes{} }
func (m *GetProjectRes) String() string { return proto.CompactTextString(m) }
func (*GetProjectRes) ProtoMessage()    {}
func (*GetProjectRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3bad42b4e7b5cf, []int{5}
}

func (m *GetProjectRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProjectRes.Unmarshal(m, b)
}
func (m *GetProjectRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProjectRes.Marshal(b, m, deterministic)
}
func (m *GetProjectRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProjectRes.Merge(m, src)
}
func (m *GetProjectRes) XXX_Size() int {
	return xxx_messageInfo_GetProjectRes.Size(m)
}
func (m *GetProjectRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProjectRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetProjectRes proto.InternalMessageInfo

func (m *GetProjectRes) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *GetProjectRes) GetRepositoryId() string {
	if m != nil {
		return m.RepositoryId
	}
	return ""
}

func (m *GetProjectRes) GetVcsId() string {
	if m != nil {
		return m.VcsId
	}
	return ""
}

func (m *GetProjectRes) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *GetProjectRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetProjectRes) GetCloneUrl() string {
	if m != nil {
		return m.CloneUrl
	}
	return ""
}

func (m *GetProjectRes) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *GetProjectRes) GetAccesstoken() string {
	if m != nil {
		return m.Accesstoken
	}
	return ""
}

func (m *GetProjectRes) GetCommitId() string {
	if m != nil {
		return m.CommitId
	}
	return ""
}

func (m *GetProjectRes) GetStoragePath() string {
	if m != nil {
		return m.StoragePath
	}
	return ""
}

func (m *GetProjectRes) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *GetProjectRes) GetShiftfile() string {
	if m != nil {
		return m.Shiftfile
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterReq)(nil), "api.RegisterReq")
	proto.RegisterType((*RegisterRes)(nil), "api.RegisterRes")
	proto.RegisterType((*UpdateBuildStatusReq)(nil), "api.UpdateBuildStatusReq")
	proto.RegisterType((*UpdateBuildStatusRes)(nil), "api.UpdateBuildStatusRes")
	proto.RegisterType((*GetProjectReq)(nil), "api.GetProjectReq")
	proto.RegisterType((*GetProjectRes)(nil), "api.GetProjectRes")
}

func init() { proto.RegisterFile("api/shift.proto", fileDescriptor_ce3bad42b4e7b5cf) }

var fileDescriptor_ce3bad42b4e7b5cf = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0xc7, 0x9b, 0xb6, 0x49, 0x37, 0x93, 0x54, 0xb4, 0x56, 0xa9, 0xdc, 0x80, 0x50, 0x59, 0x2e,
	0x48, 0x88, 0x80, 0x40, 0xe2, 0x01, 0xb8, 0x40, 0xc4, 0xa5, 0x4a, 0x55, 0x71, 0x8c, 0x1c, 0x7b,
	0x9a, 0x98, 0x6c, 0x6c, 0x63, 0x7b, 0x23, 0xf5, 0xb9, 0xb8, 0xf3, 0x42, 0xbc, 0x04, 0xf2, 0x47,
	0xba, 0x5b, 0x5a, 0xd4, 0xdb, 0xfe, 0x7f, 0xf3, 0xb1, 0xe3, 0xbf, 0xc7, 0xf0, 0x84, 0x19, 0xf9,
	0xce, 0x2d, 0xe5, 0xb5, 0x1f, 0x1b, 0xab, 0xbd, 0x26, 0x7b, 0xcc, 0xc8, 0xf2, 0x2b, 0x0c, 0xa6,
	0xb8, 0x90, 0xce, 0xa3, 0x9d, 0xe2, 0x4f, 0x72, 0x06, 0xc5, 0xbc, 0x96, 0x95, 0x98, 0x49, 0x41,
	0x3b, 0xe7, 0x9d, 0xd7, 0xfd, 0xe9, 0x41, 0xd4, 0x13, 0x41, 0x5e, 0x00, 0x18, 0x2b, 0x37, 0xcc,
	0xe3, 0x0a, 0x6f, 0xe8, 0x6e, 0x0c, 0xb6, 0x48, 0xf9, 0xb6, 0xdd, 0xc9, 0x85, 0x74, 0x9b, 0x25,
	0xa6, 0x5e, 0xc5, 0xb4, 0x45, 0xca, 0x5f, 0x1d, 0x38, 0xb9, 0x32, 0x82, 0x79, 0xfc, 0x1c, 0x7e,
	0x70, 0xe9, 0x99, 0xaf, 0xdd, 0x23, 0x23, 0x9c, 0x40, 0x77, 0x61, 0x99, 0x59, 0xe6, 0xbf, 0x27,
	0x41, 0x4e, 0xa1, 0xe7, 0x62, 0x35, 0xdd, 0x8b, 0x38, 0xab, 0x30, 0x01, 0x5f, 0x22, 0x5f, 0x19,
	0x2d, 0x95, 0xa7, 0xfb, 0x69, 0xe0, 0x86, 0x84, 0x3a, 0x8b, 0xcc, 0x69, 0x45, 0xbb, 0xa9, 0x2e,
	0x29, 0x32, 0x82, 0x42, 0xd4, 0x96, 0x79, 0xa9, 0x15, 0xed, 0xc5, 0xc8, 0xad, 0x2e, 0x4f, 0x1f,
	0x1c, 0xda, 0x95, 0xdf, 0xe1, 0xf0, 0x0b, 0xfa, 0x0b, 0xab, 0x7f, 0x20, 0xf7, 0x8f, 0x9c, 0xe2,
	0x0d, 0x1c, 0x4b, 0xc5, 0xab, 0x5a, 0xe0, 0x2c, 0x5e, 0xc7, 0xb5, 0xac, 0x30, 0x9e, 0xa8, 0x98,
	0x1e, 0xe5, 0xc0, 0xe5, 0x96, 0x97, 0x7f, 0x76, 0xef, 0x76, 0x76, 0xe4, 0x25, 0x0c, 0xb9, 0x56,
	0x9e, 0x49, 0x85, 0xb6, 0xe9, 0x3e, 0xb8, 0x65, 0x13, 0x41, 0x5e, 0xc1, 0xa1, 0x45, 0xa3, 0x9d,
	0xf4, 0xda, 0xde, 0x84, 0x9c, 0xe4, 0xd7, 0xb0, 0x81, 0x13, 0x41, 0x9e, 0x42, 0x6f, 0xc3, 0x5d,
	0x88, 0x26, 0xdb, 0xba, 0x1b, 0xee, 0x26, 0x22, 0xb8, 0x32, 0xb7, 0x4c, 0xf1, 0x65, 0x76, 0x2c,
	0x2b, 0x42, 0x60, 0x5f, 0xb1, 0x35, 0x66, 0xaf, 0xe2, 0x37, 0x79, 0x06, 0x7d, 0x5e, 0x69, 0x85,
	0xb3, 0xda, 0x56, 0x5b, 0xab, 0x22, 0xb8, 0xb2, 0x55, 0xb0, 0xb1, 0x62, 0x6a, 0x51, 0xb3, 0x05,
	0xd2, 0x83, 0x14, 0xdb, 0x6a, 0x72, 0x0e, 0x03, 0xc6, 0x39, 0x3a, 0xe7, 0xf5, 0x0a, 0x15, 0x2d,
	0xd2, 0x11, 0x5a, 0x28, 0xb6, 0xd6, 0xeb, 0xb5, 0xf4, 0x61, 0xc0, 0x7e, 0x6e, 0x1d, 0xc1, 0x44,
	0x04, 0x0b, 0x9c, 0xd7, 0x96, 0x2d, 0x70, 0x66, 0x98, 0x5f, 0x52, 0x48, 0xf5, 0x99, 0x5d, 0x30,
	0x9f, 0x96, 0x42, 0xd7, 0x96, 0x23, 0x1d, 0xe4, 0xa5, 0x88, 0x8a, 0x3c, 0x87, 0x7e, 0x63, 0xfa,
	0x30, 0x86, 0x1a, 0xf0, 0xe1, 0x77, 0x07, 0xba, 0xd1, 0x7b, 0xf2, 0x1e, 0x8a, 0xed, 0x36, 0x93,
	0xa3, 0x31, 0x33, 0x72, 0xdc, 0x7a, 0x26, 0xa3, 0x7f, 0x89, 0x2b, 0x77, 0xc8, 0x27, 0x80, 0xe6,
	0xa2, 0x08, 0x89, 0x19, 0x77, 0x76, 0x62, 0x74, 0x9f, 0x85, 0xba, 0x6f, 0x70, 0x7c, 0x6f, 0xa5,
	0xc8, 0x59, 0x4c, 0x7d, 0xe8, 0x7d, 0x8c, 0xfe, 0x1b, 0x72, 0xe5, 0xce, 0xbc, 0x17, 0x9f, 0xf6,
	0xc7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xe3, 0x49, 0x40, 0xed, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShiftClient is the client API for Shift service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShiftClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error)
	GetProject(ctx context.Context, in *GetProjectReq, opts ...grpc.CallOption) (*GetProjectRes, error)
	UpdateBuildStatus(ctx context.Context, in *UpdateBuildStatusReq, opts ...grpc.CallOption) (*UpdateBuildStatusRes, error)
}

type shiftClient struct {
	cc *grpc.ClientConn
}

func NewShiftClient(cc *grpc.ClientConn) ShiftClient {
	return &shiftClient{cc}
}

func (c *shiftClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error) {
	out := new(RegisterRes)
	err := c.cc.Invoke(ctx, "/api.Shift/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shiftClient) GetProject(ctx context.Context, in *GetProjectReq, opts ...grpc.CallOption) (*GetProjectRes, error) {
	out := new(GetProjectRes)
	err := c.cc.Invoke(ctx, "/api.Shift/GetProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shiftClient) UpdateBuildStatus(ctx context.Context, in *UpdateBuildStatusReq, opts ...grpc.CallOption) (*UpdateBuildStatusRes, error) {
	out := new(UpdateBuildStatusRes)
	err := c.cc.Invoke(ctx, "/api.Shift/UpdateBuildStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShiftServer is the server API for Shift service.
type ShiftServer interface {
	Register(context.Context, *RegisterReq) (*RegisterRes, error)
	GetProject(context.Context, *GetProjectReq) (*GetProjectRes, error)
	UpdateBuildStatus(context.Context, *UpdateBuildStatusReq) (*UpdateBuildStatusRes, error)
}

func RegisterShiftServer(s *grpc.Server, srv ShiftServer) {
	s.RegisterService(&_Shift_serviceDesc, srv)
}

func _Shift_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShiftServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Shift/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShiftServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shift_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShiftServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Shift/GetProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShiftServer).GetProject(ctx, req.(*GetProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shift_UpdateBuildStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBuildStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShiftServer).UpdateBuildStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Shift/UpdateBuildStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShiftServer).UpdateBuildStatus(ctx, req.(*UpdateBuildStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shift_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Shift",
	HandlerType: (*ShiftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Shift_Register_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _Shift_GetProject_Handler,
		},
		{
			MethodName: "UpdateBuildStatus",
			Handler:    _Shift_UpdateBuildStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/shift.proto",
}
