// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/shift.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api/shift.proto
	api/work.proto

It has these top-level messages:
	RegisterReq
	RegisterRes
	UpdateBuildStatusReq
	UpdateBuildStatusRes
	GetProjectReq
	GetProjectRes
	TopReq
	TopRes
	KillTaskReq
	KillTaskRes
	StopBuildReq
	StopBuildRes
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterReq struct {
	BuildId    string `protobuf:"bytes,1,opt,name=build_id,json=buildId" json:"build_id,omitempty"`
	Privatekey string `protobuf:"bytes,2,opt,name=privatekey" json:"privatekey,omitempty"`
}

func (m *RegisterReq) Reset()                    { *m = RegisterReq{} }
func (m *RegisterReq) String() string            { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()               {}
func (*RegisterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegisterReq) GetBuildId() string {
	if m != nil {
		return m.BuildId
	}
	return ""
}

func (m *RegisterReq) GetPrivatekey() string {
	if m != nil {
		return m.Privatekey
	}
	return ""
}

type RegisterRes struct {
	Registered bool `protobuf:"varint,1,opt,name=registered" json:"registered,omitempty"`
}

func (m *RegisterRes) Reset()                    { *m = RegisterRes{} }
func (m *RegisterRes) String() string            { return proto.CompactTextString(m) }
func (*RegisterRes) ProtoMessage()               {}
func (*RegisterRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterRes) GetRegistered() bool {
	if m != nil {
		return m.Registered
	}
	return false
}

type UpdateBuildStatusReq struct {
	BuildId    string `protobuf:"bytes,1,opt,name=build_id,json=buildId" json:"build_id,omitempty"`
	Graph      string `protobuf:"bytes,2,opt,name=graph" json:"graph,omitempty"`
	Status     string `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
	Checkpoint string `protobuf:"bytes,4,opt,name=checkpoint" json:"checkpoint,omitempty"`
}

func (m *UpdateBuildStatusReq) Reset()                    { *m = UpdateBuildStatusReq{} }
func (m *UpdateBuildStatusReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateBuildStatusReq) ProtoMessage()               {}
func (*UpdateBuildStatusReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateBuildStatusReq) GetBuildId() string {
	if m != nil {
		return m.BuildId
	}
	return ""
}

func (m *UpdateBuildStatusReq) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *UpdateBuildStatusReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateBuildStatusReq) GetCheckpoint() string {
	if m != nil {
		return m.Checkpoint
	}
	return ""
}

type UpdateBuildStatusRes struct {
}

func (m *UpdateBuildStatusRes) Reset()                    { *m = UpdateBuildStatusRes{} }
func (m *UpdateBuildStatusRes) String() string            { return proto.CompactTextString(m) }
func (*UpdateBuildStatusRes) ProtoMessage()               {}
func (*UpdateBuildStatusRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type GetProjectReq struct {
	BuildId string `protobuf:"bytes,1,opt,name=build_id,json=buildId" json:"build_id,omitempty"`
}

func (m *GetProjectReq) Reset()                    { *m = GetProjectReq{} }
func (m *GetProjectReq) String() string            { return proto.CompactTextString(m) }
func (*GetProjectReq) ProtoMessage()               {}
func (*GetProjectReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetProjectReq) GetBuildId() string {
	if m != nil {
		return m.BuildId
	}
	return ""
}

type GetProjectRes struct {
	ContainerId  string `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	RepositoryId string `protobuf:"bytes,2,opt,name=repository_id,json=repositoryId" json:"repository_id,omitempty"`
	VcsId        string `protobuf:"bytes,3,opt,name=vcs_id,json=vcsId" json:"vcs_id,omitempty"`
	Branch       string `protobuf:"bytes,4,opt,name=branch" json:"branch,omitempty"`
	Name         string `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	CloneUrl     string `protobuf:"bytes,6,opt,name=clone_url,json=cloneUrl" json:"clone_url,omitempty"`
	Language     string `protobuf:"bytes,7,opt,name=language" json:"language,omitempty"`
	Accesstoken  string `protobuf:"bytes,8,opt,name=accesstoken" json:"accesstoken,omitempty"`
	CommitId     string `protobuf:"bytes,9,opt,name=commit_id,json=commitId" json:"commit_id,omitempty"`
	StoragePath  string `protobuf:"bytes,10,opt,name=storage_path,json=storagePath" json:"storage_path,omitempty"`
	Source       string `protobuf:"bytes,11,opt,name=source" json:"source,omitempty"`
}

func (m *GetProjectRes) Reset()                    { *m = GetProjectRes{} }
func (m *GetProjectRes) String() string            { return proto.CompactTextString(m) }
func (*GetProjectRes) ProtoMessage()               {}
func (*GetProjectRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetProjectRes) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *GetProjectRes) GetRepositoryId() string {
	if m != nil {
		return m.RepositoryId
	}
	return ""
}

func (m *GetProjectRes) GetVcsId() string {
	if m != nil {
		return m.VcsId
	}
	return ""
}

func (m *GetProjectRes) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *GetProjectRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetProjectRes) GetCloneUrl() string {
	if m != nil {
		return m.CloneUrl
	}
	return ""
}

func (m *GetProjectRes) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *GetProjectRes) GetAccesstoken() string {
	if m != nil {
		return m.Accesstoken
	}
	return ""
}

func (m *GetProjectRes) GetCommitId() string {
	if m != nil {
		return m.CommitId
	}
	return ""
}

func (m *GetProjectRes) GetStoragePath() string {
	if m != nil {
		return m.StoragePath
	}
	return ""
}

func (m *GetProjectRes) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterReq)(nil), "api.RegisterReq")
	proto.RegisterType((*RegisterRes)(nil), "api.RegisterRes")
	proto.RegisterType((*UpdateBuildStatusReq)(nil), "api.UpdateBuildStatusReq")
	proto.RegisterType((*UpdateBuildStatusRes)(nil), "api.UpdateBuildStatusRes")
	proto.RegisterType((*GetProjectReq)(nil), "api.GetProjectReq")
	proto.RegisterType((*GetProjectRes)(nil), "api.GetProjectRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Shift service

type ShiftClient interface {
	Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error)
	GetProject(ctx context.Context, in *GetProjectReq, opts ...grpc.CallOption) (*GetProjectRes, error)
	UpdateBuildStatus(ctx context.Context, in *UpdateBuildStatusReq, opts ...grpc.CallOption) (*UpdateBuildStatusRes, error)
}

type shiftClient struct {
	cc *grpc.ClientConn
}

func NewShiftClient(cc *grpc.ClientConn) ShiftClient {
	return &shiftClient{cc}
}

func (c *shiftClient) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterRes, error) {
	out := new(RegisterRes)
	err := grpc.Invoke(ctx, "/api.Shift/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shiftClient) GetProject(ctx context.Context, in *GetProjectReq, opts ...grpc.CallOption) (*GetProjectRes, error) {
	out := new(GetProjectRes)
	err := grpc.Invoke(ctx, "/api.Shift/GetProject", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shiftClient) UpdateBuildStatus(ctx context.Context, in *UpdateBuildStatusReq, opts ...grpc.CallOption) (*UpdateBuildStatusRes, error) {
	out := new(UpdateBuildStatusRes)
	err := grpc.Invoke(ctx, "/api.Shift/UpdateBuildStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Shift service

type ShiftServer interface {
	Register(context.Context, *RegisterReq) (*RegisterRes, error)
	GetProject(context.Context, *GetProjectReq) (*GetProjectRes, error)
	UpdateBuildStatus(context.Context, *UpdateBuildStatusReq) (*UpdateBuildStatusRes, error)
}

func RegisterShiftServer(s *grpc.Server, srv ShiftServer) {
	s.RegisterService(&_Shift_serviceDesc, srv)
}

func _Shift_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShiftServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Shift/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShiftServer).Register(ctx, req.(*RegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shift_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShiftServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Shift/GetProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShiftServer).GetProject(ctx, req.(*GetProjectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Shift_UpdateBuildStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBuildStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShiftServer).UpdateBuildStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Shift/UpdateBuildStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShiftServer).UpdateBuildStatus(ctx, req.(*UpdateBuildStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Shift_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Shift",
	HandlerType: (*ShiftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Shift_Register_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _Shift_GetProject_Handler,
		},
		{
			MethodName: "UpdateBuildStatus",
			Handler:    _Shift_UpdateBuildStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/shift.proto",
}

func init() { proto.RegisterFile("api/shift.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x9b, 0xb6, 0x49, 0x9d, 0x49, 0x2b, 0x60, 0x54, 0xaa, 0x6d, 0x90, 0x50, 0x31, 0x17,
	0x84, 0x44, 0x40, 0x20, 0xf1, 0x00, 0x5c, 0xc0, 0xe2, 0x52, 0xa5, 0xea, 0x39, 0xda, 0xac, 0x07,
	0x7b, 0x89, 0xe3, 0x5d, 0x76, 0xc7, 0x91, 0x7a, 0xe2, 0xcd, 0x78, 0x03, 0xde, 0x09, 0xed, 0xda,
	0x25, 0x2e, 0x0d, 0x70, 0xf3, 0xf7, 0x9b, 0x3f, 0xfe, 0xc6, 0x33, 0x86, 0x07, 0xd2, 0xea, 0xd7,
	0xbe, 0xd4, 0x5f, 0x78, 0x66, 0x9d, 0x61, 0x83, 0x07, 0xd2, 0xea, 0xf4, 0x13, 0x4c, 0xe6, 0x54,
	0x68, 0xcf, 0xe4, 0xe6, 0xf4, 0x0d, 0xcf, 0x21, 0x59, 0x36, 0xba, 0xca, 0x17, 0x3a, 0x17, 0x83,
	0x8b, 0xc1, 0x8b, 0xf1, 0xfc, 0x28, 0xea, 0x2c, 0xc7, 0xa7, 0x00, 0xd6, 0xe9, 0x8d, 0x64, 0x5a,
	0xd1, 0x8d, 0xd8, 0x8f, 0xc1, 0x1e, 0x49, 0x5f, 0xf5, 0x3b, 0xf9, 0x90, 0xee, 0x3a, 0x49, 0x6d,
	0xaf, 0x64, 0xde, 0x23, 0xe9, 0x77, 0x38, 0xbd, 0xb6, 0xb9, 0x64, 0xfa, 0x10, 0xfa, 0x5f, 0xb1,
	0xe4, 0xc6, 0xff, 0xc7, 0xc1, 0x29, 0x0c, 0x0b, 0x27, 0x6d, 0xd9, 0xbd, 0xbc, 0x15, 0x78, 0x06,
	0x23, 0x1f, 0xab, 0xc5, 0x41, 0xc4, 0x9d, 0x0a, 0x06, 0x54, 0x49, 0x6a, 0x65, 0x8d, 0xae, 0x59,
	0x1c, 0xb6, 0x7e, 0xb7, 0x24, 0x3d, 0xdb, 0x69, 0xc0, 0xa7, 0x2f, 0xe1, 0xe4, 0x23, 0xf1, 0xa5,
	0x33, 0x5f, 0x49, 0xf1, 0xbf, 0x1d, 0xa5, 0x3f, 0xf7, 0xef, 0x26, 0x7b, 0x7c, 0x06, 0xc7, 0xca,
	0xd4, 0x2c, 0x75, 0x4d, 0x6e, 0x5b, 0x30, 0xf9, 0xcd, 0xb2, 0x1c, 0x9f, 0xc3, 0x89, 0x23, 0x6b,
	0xbc, 0x66, 0xe3, 0x6e, 0x42, 0x4e, 0x3b, 0xce, 0xf1, 0x16, 0x66, 0x39, 0x3e, 0x86, 0xd1, 0x46,
	0xf9, 0x10, 0x6d, 0xa7, 0x1a, 0x6e, 0x94, 0xcf, 0xf2, 0x30, 0xec, 0xd2, 0xc9, 0x5a, 0x95, 0xdd,
	0x40, 0x9d, 0x42, 0x84, 0xc3, 0x5a, 0xae, 0x49, 0x0c, 0x23, 0x8d, 0xcf, 0xf8, 0x04, 0xc6, 0xaa,
	0x32, 0x35, 0x2d, 0x1a, 0x57, 0x89, 0x51, 0x0c, 0x24, 0x11, 0x5c, 0xbb, 0x0a, 0xa7, 0x90, 0x54,
	0xb2, 0x2e, 0x1a, 0x59, 0x90, 0x38, 0x6a, 0x63, 0xb7, 0x1a, 0x2f, 0x60, 0x22, 0x95, 0x22, 0xef,
	0xd9, 0xac, 0xa8, 0x16, 0x49, 0x3b, 0x42, 0x0f, 0xc5, 0xd6, 0x66, 0xbd, 0xd6, 0x1c, 0x0c, 0x8e,
	0xbb, 0xd6, 0x11, 0x64, 0x79, 0xf8, 0x04, 0x9e, 0x8d, 0x93, 0x05, 0x2d, 0xac, 0xe4, 0x52, 0x40,
	0x5b, 0xdf, 0xb1, 0x4b, 0xc9, 0xed, 0xce, 0x4c, 0xe3, 0x14, 0x89, 0x49, 0xb7, 0xb3, 0xa8, 0xde,
	0xfe, 0x18, 0xc0, 0xf0, 0x2a, 0x9c, 0x28, 0xbe, 0x81, 0xe4, 0xf6, 0x9a, 0xf0, 0xe1, 0x4c, 0x5a,
	0x3d, 0xeb, 0x9d, 0xe9, 0xf4, 0x4f, 0xe2, 0xd3, 0x3d, 0x7c, 0x0f, 0xb0, 0x5d, 0x05, 0x62, 0xcc,
	0xb8, 0xb3, 0xc8, 0xe9, 0x7d, 0x16, 0xea, 0x3e, 0xc3, 0xa3, 0x7b, 0x77, 0x80, 0xe7, 0x31, 0x75,
	0xd7, 0x81, 0x4e, 0xff, 0x1a, 0xf2, 0xe9, 0xde, 0x72, 0x14, 0x7f, 0xad, 0x77, 0xbf, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xd0, 0x11, 0xa1, 0x36, 0x6d, 0x03, 0x00, 0x00,
}
